/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import java.io.File;
import java.io.IOException;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

import controle.Impressora;
import controle.PortaSerial;
import controle.PropertiesReader;

/**
 *
 * @author Bruno
 */
public class TelaConfig extends javax.swing.JFrame {

	/**
	 * Creates new form Tela_Config
	 */
	public TelaConfig() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jBarquivo = new javax.swing.JButton();
		jTxtUrl = new javax.swing.JTextField();
		jTxtTagReplace  = new javax.swing.JTextField();
		jCserial = new javax.swing.JComboBox<>();
		jCimpressora = new javax.swing.JComboBox<>();
		jBsalvar = new javax.swing.JButton();
		jBcancelar = new javax.swing.JButton();


		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Configuração");
		setName("Config"); // NOI18N

		jBarquivo.setText("Arquivo");
		jBarquivo.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jBarquivoActionPerformed(evt);
			}
		});

		jCserial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecione a porta--" }));

		jCimpressora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecione Impressora--"}));

		jBsalvar.setText("Salvar");
		jBsalvar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jBsalvarActionPerformed(evt);
			}
		});

		jBcancelar.setText("Cancelar");
		jBcancelar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jBcancelarActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										
										
										.addComponent(jBarquivo, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addComponent(jBcancelar))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jCserial, javax.swing.GroupLayout.PREFERRED_SIZE, 150,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jTxtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 280,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(jBsalvar).addComponent(jCimpressora,
												javax.swing.GroupLayout.PREFERRED_SIZE, 150,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(17, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(28, 28, 28)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jBarquivo)
						.addComponent(jTxtUrl, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(jCserial, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(jCimpressora, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(61, 61, 61).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(jBsalvar).addComponent(jBcancelar))
				.addContainerGap(83, Short.MAX_VALUE)));
		carregarConteudoComponentes();
		jCimpressora.setVisible(false);
		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	private void carregarConteudoComponentes() {
		try {
			PropertiesReader pr = PropertiesReader.getInstance();
			jTxtUrl.setText(pr.getUrlArquivoZPL());
			
			
			Impressora imp = new Impressora();
			for(String impressora: imp.getListaImpressoras()) {
				jCimpressora.addItem(impressora);
			}
		} catch (Exception e) {
			JOptionPane.showMessageDialog(null, "ERRO" + e);
		}

	}



	private void jBarquivoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBarquivoActionPerformed
		// Buscando arquivo e filtrando por arquivo txt
		JFileChooser fc = new JFileChooser();
		fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
		FileNameExtensionFilter filter = new FileNameExtensionFilter("Arquivo", "txt", "Txt");
		fc.setFileFilter(filter);
		fc.showOpenDialog(this);
		File f = fc.getSelectedFile();
		if(f!= null) {
			jTxtUrl.setText(f.getPath());
		}
	}// GEN-LAST:event_jBarquivoActionPerformed

	private void jBimpressoraActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBimpressoraActionPerformed
		// Listando impressoras no combo box

	}// GEN-LAST:event_jBimpressoraActionPerformed

	private void jBcancelarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBcancelarActionPerformed
		// fecha a tela config
		dispose();
	}// GEN-LAST:event_jBcancelarActionPerformed

	private void jBsalvarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBsalvarActionPerformed
		// Salva as informaçoes no properties
		if(jCserial.getSelectedIndex() == 0) {
			JOptionPane.showMessageDialog(null, "Selecione a porta Serial" );
			return;
		}
		
		if(jCimpressora.getSelectedIndex() == 0) {
			JOptionPane.showMessageDialog(null, "Selecione a impressora padraol" );
			return;
		}
		
		try {
			PropertiesReader mp = PropertiesReader.getInstance();
			mp.setUrlArquivoZPL(jTxtUrl.getText());
			mp.setPortaSerial(jCserial.getSelectedItem().toString());
			mp.setImpressoraPadrao(jCimpressora.getSelectedItem().toString());
			mp.atualizarArquivoProperties();
		} catch (IOException ex) {
			JOptionPane.showMessageDialog(null, "ERRO" + ex);
		}
		dispose();
	}// GEN-LAST:event_jBsalvarActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TelaConfig.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TelaConfig.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TelaConfig.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TelaConfig.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TelaConfig().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jBarquivo;
	private javax.swing.JButton jBcancelar;
	private javax.swing.JButton jBsalvar;
	private javax.swing.JComboBox<String> jCimpressora;
	private javax.swing.JComboBox<String> jCserial;
	private javax.swing.JTextField jTxtUrl;
	private javax.swing.JTextField jTxtTagReplace;
	// End of variables declaration//GEN-END:variables
}
