/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tela;



import Controle.Impressora;
import Controle.ManipulandoProperties;
import static Controle.ManipulandoProperties.getProp;
import Controle.Portas_Seriais;
import java.io.File;
import java.io.IOException;
import java.util.Enumeration;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Bruno
 */
public class Tela_Config extends javax.swing.JFrame {


    /**
     * Creates new form Tela_Config
     */
    public Tela_Config() {
        initComponents();
        
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jBarquivo = new javax.swing.JButton();
        jTxtUrl = new javax.swing.JTextField();
        jBserial = new javax.swing.JButton();
        jCserial = new javax.swing.JComboBox<>();
        jBimpressora = new javax.swing.JButton();
        jCimpressora = new javax.swing.JComboBox<>();
        jBsalvar = new javax.swing.JButton();
        jBcancelar = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configuração");
        setName("Config"); // NOI18N

        jBarquivo.setText("Arquivo");
        jBarquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBarquivoActionPerformed(evt);
            }
        });

        jBserial.setText("Serial");
        jBserial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBserialActionPerformed(evt);
            }
        });

        jCserial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecione a porta--" }));
        jCserial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCserialActionPerformed(evt);
            }
        });

        jBimpressora.setText("Impressora");
        jBimpressora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBimpressoraActionPerformed(evt);
            }
        });

        jCimpressora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Slecione Impressora--", " " }));

        jBsalvar.setText("Salvar");
        jBsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalvarActionPerformed(evt);
            }
        });

        jBcancelar.setText("Cancelar");
        jBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jBimpressora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBserial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBarquivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jBcancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCserial, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jBsalvar)
                        .addComponent(jCimpressora, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBarquivo)
                    .addComponent(jTxtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBserial)
                    .addComponent(jCserial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBimpressora)
                    .addComponent(jCimpressora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBsalvar)
                    .addComponent(jBcancelar))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCserialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCserialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCserialActionPerformed

    private void jBserialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBserialActionPerformed
        //Listando portas no combo box
        Portas_Seriais ps = new Portas_Seriais();
        ps.retornaPorta();
        jCserial.addItem(ps.getName_Port().toString());
        
        
        
        
    }//GEN-LAST:event_jBserialActionPerformed

    private void jBarquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBarquivoActionPerformed
      //Buscando arquivo e filtrando por arquivo txt
      JFileChooser fc = new JFileChooser();
      fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
      FileNameExtensionFilter filter = new FileNameExtensionFilter("Arquivo", "txt", "Txt");
      fc.setFileFilter(filter);
      fc.showOpenDialog(this);
      File f = fc.getSelectedFile();
      jTxtUrl.setText(f.getPath());
    }//GEN-LAST:event_jBarquivoActionPerformed

    private void jBimpressoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBimpressoraActionPerformed
        //Listando impressoras no combo box
        jCimpressora.addItem(Impressora.list_impressoras().toString());
    }//GEN-LAST:event_jBimpressoraActionPerformed

    private void jBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelarActionPerformed
       //fecha a tela config
        dispose();
    }//GEN-LAST:event_jBcancelarActionPerformed

    private void jBsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalvarActionPerformed
        //Salva as informaçoes no properties
		
        ManipulandoProperties mp = new ManipulandoProperties();
        mp.setUrl(jTxtUrl.getText());
        mp.setSerial(jCserial.getItemAt(WIDTH));
        mp.setImpressora(jCimpressora.getItemAt(WIDTH));
        try {
            getProp();
            mp.setProp();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "ERRO"+ex);
        }
        dispose();
    }//GEN-LAST:event_jBsalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Config().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBarquivo;
    private javax.swing.JButton jBcancelar;
    private javax.swing.JButton jBimpressora;
    private javax.swing.JButton jBsalvar;
    private javax.swing.JButton jBserial;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCimpressora;
    private javax.swing.JComboBox<String> jCserial;
    private javax.swing.JTextField jTxtUrl;
    // End of variables declaration//GEN-END:variables
}
